version: "3.3"
services:
  database:
    image: postgres:12
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  gruzmaster_back:
    container_name: gruzmaster_back
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    volumes:
      - .:/gruzmaster_back
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/gruzmaster_back/node_modules
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@database
volumes:
  gem_cache:
  db_data:
  node_modules:
