default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  username: postgres
  password: password

development:
  <<: *default
  database: gruzmaster_back_development
test:
  <<: *default
  database: gruzmaster_back_test
production:
  <<: *default
  database: gruzmaster_back_production
  username: gruzmaster_back
  password: <%= ENV['DEVISE_JWT_APP_DATABASE_PASSWORD'] %>
